services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sistem_crm
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  api:
    build: ./api
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"
  web:
    build: ./web
    environment:
      - VITE_API_URL=http://localhost:8081
    ports:
      - "8080:8080"
    depends_on:
      - api
  nginx:
    image: nginx:alpine
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  pgdata:
