version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/crm
    depends_on:
      - postgres
    ports:
      - '8081:3000'

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - '8080:4173'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8082:8080'

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api

volumes:
  pgdata:
